name: Android Cross-Compile

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 关键修复：使用新版 NDK 安装 Action
    - name: Setup Android NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: "25.2.9519653"  # 指定 NDK 版本

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        
        # 根据 ABI 选择配置
        if [ "${{ matrix.abi }}" = "arm64-v8a" ]; then
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_NDK=$ANDROID_NDK_ROOT \
            -DANDROID_PLATFORM=android-21 \
            -DSTATIC_LIB_PATH=../jni/static-libs/arm64-v8a
        else
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_NDK=$ANDROID_NDK_ROOT \
            -DANDROID_PLATFORM=android-16 \
            -DSTATIC_LIB_PATH=../jni/static-libs/armeabi-v7a
        fi

    - name: Build project
      run: |
        cd build
        cmake --build . --target native-lib -- -j $(nproc)

    - name: Collect artifacts
      run: |
        mkdir -p artifacts/${{ matrix.abi }}
        cp build/libnative-lib.so artifacts/${{ matrix.abi }}
        cp -r jni/include artifacts/
        cp -r jni/static-libs artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-libs
        path: artifacts